# Generated by Django 3.2 on 2021-04-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfPerson', models.IntegerField()),
                ('ticket_price', models.FloatField()),
                ('user', models.CharField(default='', max_length=500)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.show')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.show')),
            ],
        ),
    ]
