# Generated by Django 3.2 on 2021-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='./')),
                ('ticket_price', models.FloatField()),
            ],
        ),
    ]
