# Generated by Django 3.2 on 2021-04-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_show'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('screen', 'timing', 'date')},
        ),
    ]
